[DEFAULT]

[ProcessGroup]

clients:                general 
label:                  Archive data records into database 

[general]

command:                store_general.py
label:                  Store data records 

poll.newsgroups:        transport.*.greenline
                        transport.*.redline

poll.catchup:           0
poll.newsserver:        localhost
poll.newsserver.port:   1119

# Enable for debugging

poll.exit_on_error:     true
poll.rate.at_start:     true
poll.rate.sync:         true
#log.level:              debug

