export DATA_TRANSPORT_PATH=$PWD
export UV_CACHE_DIR=$DATA_TRANSPORT_PATH/.local/cache
export UV_PYTHON_INSTALL_DIR=$DATA_TRANSPORT_PATH/.local/python
export UV_PYTHON_BIN_DIR=$DATA_TRANSPORT_PATH/.local/bin

