[DEFAULT]

# See ../processing.conf for SQL parameters

product:        level1
formats:        hdf5 

output.path:    %(path.project.archive)s/<station>/<instrument>/<product>/%%Y/%%j
output.name:    mango-<station>-<instrument>-<product>-%%Y%%m%%d
output:         %(output.path)s/%(output.name)s.<ext>

ncores:         6
task.cmd:       mango-process-raw-images -n %(ncores)s -f <filelist> -o %(output)s 

news.reprocess: %(news.watch)s.level1

[ProcessGroup]

clients:            daily reprocess watch
label:              Level1 data processing

[daily]

command:            processing_daily.py
label:              Generate daily level1 data products

schedule.at:        16:30:00 
run_at_start:       true 
max_retries:        5

restrict:           bdr-greenline 
                    blo-greenline
                    cfs-greenline
                    cfs-redline
                    cvo-greenline
                    cvo-redline
                    eio-redline
                    low-greenline
                    mdk-redline
                    mro-greenline
                    mto-redline
                    new-greenline
                    par-redline
                    ovi-greenline
                    pfo-greenline
                    lao-redline

exit_on_error:      true 

[reprocess]

command:            processing_redo.py
label:              Regenerate level1 data products 

poll.catchup:       0

poll.newsgroups:    %(news.reprocess)s
poll.exit_on_error: true
poll.rate.at_start: true


[watch]

command:            filewatch
label:              Post reprocess requests

post.newsgroup:     %(news.reprocess)s
watch.path:         /data/transport/mango/watch/reprocess/level1
watch.files:        *

