[DEFAULT]

# See ../processing.conf for SQL parameters

product:            quicklook
formats:            mp4 webm

output.path:        %(path.project.archive)s/<station>/<instrument>/<product>/%%Y/%%j
output.name:        mango-<station>-<instrument>-<product>-%%Y%%m%%d
output:             %(output.path)s/%(output.name)s.<ext>

#task.cmd:           %(path.processing)s/mango-quicklook-movies -f <filelist> -o %(output)s
task.cmd:           mango-quicklook-movies -f <filelist> -o %(output)s

news.reprocess:     %(news.watch)s.quicklook

[ProcessGroup]

clients:            daily reprocess watch
label:              Quicklook movie processing

[daily]

command:            processing_daily.py
label:              Generate daily quicklook movies 

schedule.at:        16:30:00 
run_at_start:       true 
max_retries:        5

exit_on_error:      true 
#log.level:          debug

[reprocess]

command:            processing_redo.py
label:              Reprocess quicklook movies 

poll.catchup:       0

poll.newsgroups:    %(news.reprocess)s
poll.exit_on_error: true
poll.rate.at_start: true


[watch]

command:            filewatch
label:              Post reprocess requests

post.newsgroup:     %(news.reprocess)s
watch.path:         /data/transport/mango/watch/reprocess/quicklook
watch.files:        *

