[DEFAULT]

# See ../processing.conf for SQL parameters

product:        quicklook
formats:        mp4 webm

output.path:    %(path.project.archive)s/<station>/<instrument>/<product>/%%Y/%%j
output.name:    mango-<station>-<instrument>-<product>-%%Y%%m%%d
output:         %(output.path)s/%(output.name)s.<ext>

task.cmd:       %(path.processing)s/mango-quicklook-movies -f <filelist> -o %(output)s

news.reprocess: %(news.watch)s.quicklook

[ProcessGroup]

clients:            daily reprocess watch
label:              Quicklook movie processing

[daily]

command:            processing_daily.py
label:              Generate daily quicklook movies 

schedule.at:        16:30:00 
runAtStart:         true 
maxRetries:         5

#exitOnError:       true 

[reprocess]

command:            processing_redo.py
label:              Reprocess quicklook movies 

poll.catchup:       0

poll.newsgroups:    %(news.reprocess)s
poll.exitOnError:   true
poll.rate.atStart:  true


[watch]

command:            filewatch
label:              Post reprocess requests

post.newsgroup:     %(news.reprocess)s
watch.path:         /data/transport/mango/watch/reprocess/quicklook
watch.files:        *

