#!/bin/sh

set -o errexit  # abort on nonzero exitstatus
set -o nounset  # abort on unbound variable
set -o pipefail # do not hide errors within pipes

PROJECT=uptime-plot

SCRIPTDIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null 2>&1 && pwd )"
BASEDIR=$(realpath $SCRIPTDIR/../..)

PROJECT_CONTRIB=$BASEDIR/contrib/$PROJECT
PROJECT_VAR=$BASEDIR/var/$PROJECT
VENV=$PROJECT_VAR/venv

: ${PYTHON:=python3}

mkdir -p $PROJECT_VAR

rm -rf $VENV

echo "PYTHON=$PYTHON"
echo "Installing into $VENV"

$PYTHON -m venv $VENV 
. $VENV/bin/activate

pip install -U pip
pip install -r $PROJECT_CONTRIB/requirements.txt


